# Generated by Django 4.1 on 2022-08-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl3',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl4',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='imageUrl5',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(blank=True),
        ),
    ]
